# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "jekyll"

gem "webrick", "~> 1.7"

gem "jekyll-paginate", "~> 1.1"

gem "jekyll-sitemap", "~> 1.4"

gem "jekyll-gist", "~> 1.5"

gem "jekyll-feed", "~> 0.16.0"
